### ISSUE TITLE
P2BNet on DOTA

### ISSUE THREAD

**Issue by lo202ng** [ucas-vg/P2BNet#11]
I have tried to train on DOTA using the COCO config, but got a bad result, the minimum loss displayed when training was more than 0.1, and the pseudo box in visualization is terrible. Does this model not apply to remote sensing data sets? these are one pic of my results and train information:
![00004](https://user-images.githubusercontent.com/81849106/223048783-40b20a6d-2408-451f-93fc-8f1f2b491a19.jpg)

![image](https://user-images.githubusercontent.com/81849106/223048717-c9256b97-2c88-4791-8939-3f2e42b0aa31.png)

**Comment by Darren-pfchen** [comment]
The anchor setting and learning rate  can be changed in DOTA to adapt to the object scale. We have no time to adjust it now and we will try it in following work. Thanks!

**Comment by lo202ng** [comment]
thanks for your replay, I'll try it~
