### ISSUE TITLE
About the reproduction of this paper.

### ISSUE THREAD

**Issue by Colezwhy** [ucas-vg/P2BNet#14]
Hi, i am very interested about the new method, i wonder if the baseline of this paper can be reproduced stably? Since when i use my computational resource to train this network, i find it hard to reach the same precision as in the paper. Thanks for your excellent work!

**Comment by Darren-pfchen** [comment]
How many gpus you used （our default is 8*RTX3090（24G）） and have you changed the configs？

**Comment by Colezwhy** [comment]
Thank you for your reply, i've finished that. Great work!
