### ISSUE TITLE
P2BNet的核心模块是哪里？

### ISSUE THREAD

**Issue by SchulerYan** [ucas-vg/P2BNet#15]

**Comment by Darren-pfchen** [comment]
mmdet/models/detectors/P2BNet.py里有CBP和PBR的采样，mmdet/models/roi_heads/P2B_head.py（120-179）的_bbox_forward_train()有loss和merge

**Comment by SchulerYan** [comment]
您好，我是燕舒乐，您的邮件我已查收。此为自动回复。
