### ISSUE TITLE
What is the meaning of "off-the-shelf proposal"?

### ISSUE THREAD

**Issue by csEylLee** [ucas-vg/P2BNet#9]
Hello! What is the meaning of "off-the-shelf proposal"? As a freshman, I can't understand it. Sincerely, hope for your answer. (You can answer in Chinese or English, I can read Chinese. )

**Comment by Darren-pfchen** [comment]
"off-the-shelf proposal" means the style like selective search. The results of selective search can be saved offline, and the network read those as the proposals (like fast rcnn).  
如果用中文说的话，就是那些通过selective search这种无监督方法生成1000个候选框供后面网络使用，而不是像faster的rpn那样子通过网络学习。弱监督之前的方法里面很多都是这样做的。我们之所以用"off-the-shelf proposal"这个词是因为之前一些论文把它称作为这个。
